bsub -q gsla-cpu -R rusage[mem=4200] -J yoyo /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 32  --genome_size 128 --beta 0.5 --rho 0.25 --mating_strategy all_vs_all


bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 7 --genome_size 128 --beta 0.1 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/7gen_128genomes_0.1beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 7 --genome_size 128 --beta 0.2 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/7gen_128genomes_0.2beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 7 --genome_size 128 --beta 0.3 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/7gen_128genomes_0.3beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 7 --genome_size 128 --beta 0.4 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/7gen_128genomes_0.4beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 7 --genome_size 128 --beta 0.5 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/7gen_128genomes_0.5beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 7 --genome_size 128 --beta 0.6 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/7gen_128genomes_0.6beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 7 --genome_size 128 --beta 0.7 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/7gen_128genomes_0.7beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 7 --genome_size 128 --beta 0.8 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/7gen_128genomes_0.8beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 7 --genome_size 128 --beta 0.9 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/7gen_128genomes_0.9beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 6 --genome_size 128 --beta 0.1 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/6gen_128genomes_0.1beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 6 --genome_size 128 --beta 0.2 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/6gen_128genomes_0.2beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 6 --genome_size 128 --beta 0.3 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/6gen_128genomes_0.3beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 6 --genome_size 128 --beta 0.4 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/6gen_128genomes_0.4beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 6 --genome_size 128 --beta 0.5 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/6gen_128genomes_0.5beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 6 --genome_size 128 --beta 0.6 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/6gen_128genomes_0.6beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 6 --genome_size 128 --beta 0.7 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/6gen_128genomes_0.7beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 6 --genome_size 128 --beta 0.8 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/6gen_128genomes_0.8beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 6 --genome_size 128 --beta 0.9 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/6gen_128genomes_0.9beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 8 --genome_size 128 --beta 0.1 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/8gen_128genomes_0.1beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 8 --genome_size 128 --beta 0.2 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/8gen_128genomes_0.2beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 8 --genome_size 128 --beta 0.3 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/8gen_128genomes_0.3beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 8 --genome_size 128 --beta 0.4 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/8gen_128genomes_0.4beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 8 --genome_size 128 --beta 0.5 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/8gen_128genomes_0.5beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 8 --genome_size 128 --beta 0.6 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/8gen_128genomes_0.6beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 8 --genome_size 128 --beta 0.7 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/8gen_128genomes_0.7beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 8 --genome_size 128 --beta 0.8 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/8gen_128genomes_0.8beta_0.25rho_all_vs_all
bsub -q gsla-cpu -R rusage[mem=82000] /home/labs/pilpel/barc/sexy_yeast/src/main_simulation_BC.py --generations 8 --genome_size 128 --beta 0.9 --rho 0.25 --mating_strategy all_vs_all --output_dir /home/labs/pilpel/barc/sexy_yeast/8gen_128genomes_0.9beta_0.25rho_all_vs_all


